<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>tbx</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ToolBox.Commands\ToolBox.Commands.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Terminal.Gui" Version="2.4.17" />
  </ItemGroup>

</Project>
